app:
  build: .
  command: ./from_shell.sh
  #command: /bin/bash
  #stdin_open: true
  #tty: true
  ports:
    - "4567:4567"
  volumes:
    - .:/app
  volumes_from:
    - box

box:
  image: busybox
  volumes:
    - /box
